apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}-headless
  namespace: {{.Namespace}}
  labels:
    app.kubernetes.io/instance: {{.Namespace}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 6.2.20
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: tcp-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: {{.Namespace}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 6.2.20
    app.kubernetes.io/component: redis
  sessionAffinity: None
  type: ClusterIP
