apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    app.kubernetes.io/instance: {{.Namespace}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 6.2.20
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{.PasswordB64}}
