apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{.Namespace}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 3.1.8
    app.kubernetes.io/component: dolphinscheduler
  name: {{.Name}}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-0
    port: 12345
    protocol: TCP
    targetPort: 12345
    nodePort: 30886
  selector:
    app.kubernetes.io/instance: {{.Namespace}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 3.1.8
  sessionAffinity: None
  type: NodePort